name: Deploy to HostGator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependências
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Criar arquivo .htaccess
      run: |
        cat > ./dist/.htaccess << 'EOL'
        <IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
        </IfModule>

        # Enable compression for better performance
        <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/x-javascript application/json
        </IfModule>

        # Set caching headers
        <IfModule mod_expires.c>
          ExpiresActive On
          ExpiresByType image/jpg "access plus 1 year"
          ExpiresByType image/jpeg "access plus 1 year"
          ExpiresByType image/gif "access plus 1 year"
          ExpiresByType image/png "access plus 1 year"
          ExpiresByType image/svg+xml "access plus 1 year"
          ExpiresByType text/css "access plus 1 month"
          ExpiresByType application/pdf "access plus 1 month"
          ExpiresByType text/x-javascript "access plus 1 month"
          ExpiresByType application/javascript "access plus 1 month"
          ExpiresByType application/x-javascript "access plus 1 month"
          ExpiresByType application/x-shockwave-flash "access plus 1 month"
          ExpiresByType image/x-icon "access plus 1 year"
          ExpiresDefault "access plus 2 days"
        </IfModule>
        EOL
      
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
        dangerous-clean-slate: true
